name: training_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - napari
  - pyqt
  - opencv
  - pip
  - pytorch
  - rasterio
  - rioxarray
  #- mkl=2024.0.0 # temp workaround, see https://github.com/pytorch/pytorch/issues/123097
  - pip:
      - cellpose
      - squidpy
      - napari-spatialdata
      - spatialdata-plot
      - git+https://github.com/saeyslab/harpy.git@main#egg=harpy-analysis[test,basic,opencv,clustering,cellpose,instanseg]
      #- sopa
      - bokeh
      - ipython
      - ipykernel
