name: training_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.8
  - napari
  - pyqt
  - opencv
  - pip
  - pytorch
  - rasterio
  - rioxarray
  #- mkl=2024.0.0 # temp workaround, see https://github.com/pytorch/pytorch/issues/123097
  - pip:
      - scanpy==1.10.3 # temp workaround, wait for this issue in spatialdata-plot te be resolved: https://github.com/scverse/spatialdata-plot/issues/389
      - cellpose
      - bioio
      - bioio-ome-tiff
      - bioio-tifffile
      - napari-spatialdata
      - spatialdata-plot
      - git+https://github.com/saeyslab/harpy.git@main#egg=sparrow[testing]
      - sopa
      - ipython
      - ipykernel

#pip install git+https://github.com/saeyslab/harpy.git@main\#egg\=sparrow\[testing,cli,clustering\]