name: training_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - opencv
  - pip
  - rasterio
  - pip:
      - torch
      - cellpose
      - rioxarray
      - ipython
      - ipykernel

#pip cache purge
#pip install git+https://github.com/saeyslab/harpy.git@main#egg=harpy-analysis[testing,cli] --no-cache-dir

#srun --account=lp_edu_ont2024 --clusters=genius --partition=interactive --ntasks 1 --cpus-per-task 8 --mem=16G --time=08:00:00 --pty bash