name: training_env
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - opencv
  - pip
  - rasterio
  - pip:
      - torch
      - cellpose
      - bioio
      - bioio-ome-tiff
      - bioio-tifffile
      - git+https://github.com/saeyslab/harpy.git@SC_32_vib_training#egg=sparrow[testing,cli,clustering]
      - ipython
      - ipykernel
