name: training_env
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - gdal
  - opencv
  - pip
  - rasterio
  - pip:
      - torch
      - cellpose
      - rioxarray
      #- git+https://github.com/saeyslab/harpy.git@main#egg=sparrow[testing,cli]
      - ipython
      - ipykernel

#pip cache purge
#pip install git+https://github.com/saeyslab/harpy.git@main#egg=sparrow[testing,cli] --no-cache-dir